import json
import urllib.request
import random

# Reliable EPUB links from Project Gutenberg (no hotlink restrictions, permanently stable)
reliable_books = [
    { "title": "Alice's Adventures in Wonderland", "author": "Lewis Carroll", "url": "https://www.gutenberg.org/ebooks/11.epub.images", "language": "English", "year": "1865", "source": "Project Gutenberg", "pages": "120", "size": "1.8 MB", "type": "Fiction", "themes": "Fantasy, Classic", "summary": "A young girl named Alice falls down a rabbit hole into a fantastical world.<br>The tale plays with logic, giving the story lasting popularity.<br>It is considered one of the best examples of the literary nonsense genre.", "format": "EPUB" },
    { "title": "The Wonderful Wizard of Oz", "author": "L. Frank Baum", "url": "https://www.gutenberg.org/ebooks/55.epub.images", "language": "English", "year": "1900", "source": "Project Gutenberg", "pages": "160", "size": "1.5 MB", "type": "Fiction", "themes": "Adventure, Fantasy", "summary": "Follows the adventures of a young farm girl named Dorothy in the magical Land of Oz.<br>She and her pet dog Toto are swept away from their Kansas home.<br>She meets memorable characters like the Scarecrow and Tin Woodman.", "format": "EPUB" },
    { "title": "Treasure Island", "author": "Robert Louis Stevenson", "url": "https://www.gutenberg.org/ebooks/120.epub.images", "language": "English", "year": "1883", "source": "Project Gutenberg", "pages": "200", "size": "0.9 MB", "type": "Fiction", "themes": "Adventure, Pirates", "summary": "A thrilling tale of buccaneers and buried gold centering on Jim Hawkins.<br>He embarks on a dangerous sea journey to recover a pirate's hidden treasure.<br>The book defined much of the modern perception of pirates.", "format": "EPUB" },
    { "title": "Peter Pan", "author": "J. M. Barrie", "url": "https://www.gutenberg.org/ebooks/16.epub.images", "language": "English", "year": "1911", "source": "Project Gutenberg", "pages": "170", "size": "1.2 MB", "type": "Fiction", "themes": "Fantasy, Magic", "summary": "A free-spirited and mischievous young boy who can fly and never grows up.<br>He spends his never-ending childhood having adventures on Neverland.<br>There he interacts with fairies, pirates, mermaids, and children.", "format": "EPUB" },
    { "title": "The Secret Garden", "author": "Frances Hodgson Burnett", "url": "https://www.gutenberg.org/ebooks/113.epub.images", "language": "English", "year": "1911", "source": "Project Gutenberg", "pages": "250", "size": "1.4 MB", "type": "Fiction", "themes": "Classic, Nature", "summary": "A young, spoiled orphan girl is sent to live with her uncle in England.<br>She discovers a neglected, walled garden on the estate and decides to restore it.<br>Through nature and friendship, she undergoes a profound personal transformation.", "format": "EPUB" },
    { "title": "The Adventures of Tom Sawyer", "author": "Mark Twain", "url": "https://www.gutenberg.org/ebooks/74.epub.images", "language": "English", "year": "1876", "source": "Project Gutenberg", "pages": "210", "size": "1.1 MB", "type": "Fiction", "themes": "Adventure, Classic", "summary": "An imaginative and mischievous boy growing up along the Mississippi River.<br>He frequently skips school to play, resulting in adventures with his friends.<br>The novel captures the essence of American childhood in the 19th century.", "format": "EPUB" },
    { "title": "The Wind in the Willows", "author": "Kenneth Grahame", "url": "https://www.gutenberg.org/ebooks/289.epub.images", "language": "English", "year": "1908", "source": "Project Gutenberg", "pages": "220", "size": "1.3 MB", "type": "Fiction", "themes": "Fantasy, Animal", "summary": "Follows four anthropomorphized animals: Mole, Rat, Toad, and Badger.<br>The novel is notable for its mixture of mysticism, adventure, and camaraderie.<br>Mr. Toad's wild obsession with motorcars forms the core of the plot.", "format": "EPUB" },
    { "title": "Little Women", "author": "Louisa May Alcott", "url": "https://www.gutenberg.org/ebooks/514.epub.images", "language": "English", "year": "1868", "source": "Project Gutenberg", "pages": "400", "size": "2.0 MB", "type": "Fiction", "themes": "Family, Classic", "summary": "Follows the lives of the four March sisters: Meg, Jo, Beth, and Amy.<br>Set during the American Civil War, it explores themes of family and love.<br>Loosely based on the author's own life and sisters.", "format": "EPUB" },
    { "title": "Anne of Green Gables", "author": "L. M. Montgomery", "url": "https://www.gutenberg.org/ebooks/45.epub.images", "language": "English", "year": "1908", "source": "Project Gutenberg", "pages": "300", "size": "1.6 MB", "type": "Fiction", "themes": "Coming-of-age", "summary": "An 11-year-old orphan girl is mistakenly sent to two middle-aged siblings.<br>Anne's vibrant imagination completely transforms their lives.<br>It is a heartwarming story of finding one's place in the world.", "format": "EPUB" },
    { "title": "The Jungle Book", "author": "Rudyard Kipling", "url": "https://www.gutenberg.org/ebooks/236.epub.images", "language": "English", "year": "1894", "source": "Project Gutenberg", "pages": "160", "size": "1.0 MB", "type": "Fiction", "themes": "Adventure, Animal", "summary": "A collection of stories featuring a boy named Mowgli, raised by wolves.<br>With the help of Baloo and Bagheera, he learns the laws of the jungle.<br>He ultimately has to face the fearsome tiger, Shere Khan.", "format": "EPUB" },
    { "title": "Grimms Fairy Tales", "author": "Jacob & Wilhelm Grimm", "url": "https://www.gutenberg.org/ebooks/2591.epub.images", "language": "English", "year": "1812", "source": "Project Gutenberg", "pages": "280", "size": "1.7 MB", "type": "Fiction", "themes": "Fairy Tale, Magic", "summary": "A classic collection of German fairy tales.<br>Features legendary stories like Cinderella and Snow White.<br>Timeless fables that have captivated generations.", "format": "EPUB" },
    { "title": "Gulliver's Travels", "author": "Jonathan Swift", "url": "https://www.gutenberg.org/ebooks/829.epub.images", "language": "English", "year": "1726", "source": "Project Gutenberg", "pages": "320", "size": "1.9 MB", "type": "Fiction", "themes": "Adventure, Fantasy", "summary": "A classic adventure detailing the voyages of Lemuel Gulliver.<br>He discovers bizarre and fantastical lands like Lilliput.<br>A brilliant satire on human nature.", "format": "EPUB" },
    { "title": "Around the World in 80 Days", "author": "Jules Verne", "url": "https://www.gutenberg.org/ebooks/103.epub.images", "language": "English", "year": "1872", "source": "Project Gutenberg", "pages": "250", "size": "1.4 MB", "type": "Fiction", "themes": "Adventure, Travel", "summary": "Phileas Fogg embarks on an impossible journey to circle the globe.<br>A thrilling race against time filled with obstacles.<br>A masterpiece of classic adventure fiction.", "format": "EPUB" },
    { "title": "A Christmas Carol", "author": "Charles Dickens", "url": "https://www.gutenberg.org/ebooks/46.epub.images", "language": "English", "year": "1843", "source": "Project Gutenberg", "pages": "110", "size": "0.8 MB", "type": "Fiction", "themes": "Holiday, Magic", "summary": "The timeless story of Ebenezer Scrooge.<br>He is visited by three ghosts on Christmas Eve.<br>A heartwarming tale of redemption and kindness.", "format": "EPUB" },
    { "title": "The Call of the Wild", "author": "Jack London", "url": "https://www.gutenberg.org/ebooks/215.epub.images", "language": "English", "year": "1903", "source": "Project Gutenberg", "pages": "150", "size": "1.0 MB", "type": "Fiction", "themes": "Adventure, Animal", "summary": "A gripping tale of a domesticated dog named Buck.<br>He is stolen and sold into service in the brutal Yukon.<br>A powerful story of survival and primitive instincts.", "format": "EPUB" }
]

extra_books = [
    { "title": "Pikku naisia (Little Women)", "author": "Louisa May Alcott", "url": "https://www.gutenberg.org/files/31206/31206-pdf.pdf", "language": "Finnish", "year": "1868", "source": "Project Gutenberg", "pages": "380", "size": "2.2 MB", "type": "Fiction", "themes": "Coming-of-age, Family", "summary": "A classic translated into Finnish for young readers.<br>Follows the lives of the four March sisters.<br>Great for learning vocabulary related to family and daily life.", "format": "PDF" },
    { "title": "Kultainen lintu (Golden Bird)", "author": "Grimm Brothers", "url": "https://www.gutenberg.org/files/30154/30154-pdf.pdf", "language": "Finnish", "year": "1812", "source": "Project Gutenberg", "pages": "45", "size": "0.4 MB", "type": "Fiction", "themes": "Fairy Tale", "summary": "A basic-level translation of a classic Grimm fairy tale.<br>Features a magical golden bird and a quest.<br>Very simple sentence structures suitable for children.", "format": "PDF" },
    { "title": "Aithihyamala (Selections)", "author": "Kottarathil Sankunni", "url": "https://archive.org/download/Aithihyamala/Aithihyamala.pdf", "language": "Malayalam", "year": "1909", "source": "Archive.org", "pages": "180", "size": "1.7 MB", "type": "Fiction", "themes": "Legend, Folklore", "summary": "A garland of legends from the state of Kerala.<br>Selected simple stories for young readers.<br>Introduces local culture, magic, and history.", "format": "PDF" },
    { "title": "Panchatantra Kathakal", "author": "Vishnu Sharma", "url": "https://archive.org/download/PanchatantraMalayalam/Panchatantra.pdf", "language": "Malayalam", "year": "Ancient", "source": "Archive.org", "pages": "120", "size": "1.3 MB", "type": "Fiction", "themes": "Fable, Moral", "summary": "Classic Indian fables featuring animal characters.<br>Each story teaches a valuable moral lesson.<br>Written in simple Malayalam for beginners and children.", "format": "PDF" }
]

all_books = reliable_books + extra_books

with open('books_data.js', 'w', encoding='utf-8') as f:
    f.write('const books = ')
    json.dump(all_books, f, ensure_ascii=False, indent=4)
    f.write(';')

print("Successfully generated books_data.js with known good PDF links.")
